import type { LegalBlock } from "@/lib/legal/types";

export const blocks: LegalBlock[] = [
  { type: "p", text: `Effective date: [INSERT DATE]` },
  { type: "p", text: `This Acceptable Use Policy explains what is not allowed when using AdeHQ. It applies to all users, workspaces, AI employees, integrations, uploaded content, prompts, outputs, tools, and browser/search features.` },
  { type: "p", text: `You may not use AdeHQ to:` },
  { type: "h2", text: `1. Break the law` },
  { type: "ul", items: [
      `violate applicable laws or regulations`,
      `facilitate illegal activity`,
      `evade law enforcement or regulatory obligations`,
      `infringe intellectual property, privacy, or contractual rights`,
    ] },
  { type: "h2", text: `2. Harm people` },
  { type: "ul", items: [
      `harass, threaten, abuse, or exploit others`,
      `generate hateful, discriminatory, or demeaning content`,
      `create instructions for violence or serious harm`,
      `target vulnerable people`,
      `impersonate others without permission`,
    ] },
  { type: "h2", text: `3. Abuse AI or automation` },
  { type: "ul", items: [
      `run spam, phishing, or mass unsolicited outreach`,
      `generate deceptive reviews, fake engagement, or fake identities`,
      `bypass platform rules or rate limits`,
      `scrape protected data`,
      `use browser/search features to access unauthorised or protected systems`,
      `automate actions that require human approval`,
    ] },
  { type: "h2", text: `4. Compromise security` },
  { type: "ul", items: [
      `upload malware`,
      `attempt unauthorised access`,
      `probe, scan, or test systems without permission`,
      `extract secrets or credentials`,
      `interfere with platform integrity`,
      `reverse engineer the service except as legally permitted`,
    ] },
  { type: "h2", text: `5. Misuse sensitive data` },
  { type: "ul", items: [
      `upload unnecessary special category data`,
      `upload secrets, API keys, passwords, or credentials`,
      `process regulated data without appropriate safeguards`,
      `use AdeHQ for high-risk decisions without human review and legal compliance`,
    ] },
  { type: "h2", text: `6. High-risk use` },
  { type: "p", text: `You may not use AdeHQ as the sole basis for decisions involving:` },
  { type: "ul", items: [
      `employment`,
      `credit`,
      `insurance`,
      `housing`,
      `legal rights`,
      `medical care`,
      `safety-critical systems`,
      `law enforcement`,
      `immigration`,
      `education admissions`,
      `access to essential services`,
    ] },
  { type: "p", text: `unless we have expressly agreed in writing and appropriate safeguards are in place.` },
  { type: "h2", text: `7. Enforcement` },
  { type: "p", text: `We may remove content, disable features, suspend accounts, restrict workspaces, or terminate access if we believe this policy has been violated or if use creates risk to AdeHQ, users, third parties, or the public.` },
];
