import type { LegalBlock } from "@/lib/legal/types";

export const blocks: LegalBlock[] = [
  { type: "p", text: `Effective date: [INSERT DATE]` },
  { type: "p", text: `AdeHQ uses artificial intelligence to help users create, research, plan, write, summarise, organise, and operate. This policy explains important rules for AI features.` },
  { type: "h2", text: `1. AI outputs are not guaranteed` },
  { type: "p", text: `AI-generated outputs may be inaccurate, incomplete, outdated, biased, unsafe, or unsuitable. You are responsible for reviewing and verifying outputs before relying on them.` },
  { type: "h2", text: `2. Human approval is required for important actions` },
  { type: "p", text: `AI employees may draft, suggest, summarise, research, and prepare work. Sensitive actions should require human approval, including:` },
  { type: "ul", items: [
      `sending emails`,
      `publishing content`,
      `submitting forms`,
      `making purchases`,
      `modifying production systems`,
      `deleting data`,
      `accessing sensitive integrations`,
      `making decisions with legal, financial, medical, employment, or safety implications`,
    ] },
  { type: "h2", text: `3. No professional advice` },
  { type: "p", text: `AI outputs do not constitute legal, financial, tax, medical, employment, security, or regulatory advice. Consult qualified professionals where appropriate.` },
  { type: "h2", text: `4. User responsibility` },
  { type: "p", text: `You are responsible for:` },
  { type: "ul", items: [
      `prompts you submit`,
      `data you upload`,
      `instructions you give AI employees`,
      `outputs you approve or use`,
      `compliance with applicable laws`,
      `checking accuracy and suitability`,
      `managing workspace permissions and approvals`,
    ] },
  { type: "h2", text: `5. AI providers` },
  { type: "p", text: `AdeHQ may route AI requests through different model providers, AI gateways, search providers, browser providers, and infrastructure providers. Providers may change over time for reliability, cost, quality, or availability.` },
  { type: "h2", text: `6. AI Work Hours` },
  { type: "p", text: `AI Work Hours are an abstraction for hosted AI capacity. They are not literal time, guaranteed labour, or guaranteed output. Different AI features may consume capacity at different rates.` },
  { type: "h2", text: `7. Output ownership` },
  { type: "p", text: `Subject to our Terms, you may use AI outputs generated from your lawful inputs. You are responsible for determining whether outputs are suitable for your intended use and whether any third-party rights or restrictions apply.` },
  { type: "h2", text: `8. Similarity of outputs` },
  { type: "p", text: `AI systems may generate similar or identical outputs for different users. We do not guarantee exclusivity of AI-generated content.` },
  { type: "h2", text: `9. Safety and abuse` },
  { type: "p", text: `We may monitor usage metadata, apply automated or manual safeguards, restrict certain prompts, block outputs, or suspend access to prevent abuse, security risks, legal risk, or policy violations.` },
];
