import type { LegalBlock } from "@/lib/legal/types";

export const blocks: LegalBlock[] = [
  { type: "p", text: `Effective date: [INSERT DATE]` },
  { type: "p", text: `This Cookie Policy explains how NexCache Limited, trading as AdeHQ (“AdeHQ”, “we”, “us”, or “our”), uses cookies and similar technologies on our websites and services.` },
  { type: "p", text: `Cookies are small text files placed on your device. Similar technologies include pixels, local storage, session storage, SDKs, and device identifiers.` },
  { type: "h2", text: `1. How we use cookies` },
  { type: "p", text: `We use cookies and similar technologies to:` },
  { type: "ul", items: [
      `provide core website and app functionality`,
      `authenticate users and keep sessions secure`,
      `remember settings and preferences`,
      `prevent fraud and abuse`,
      `measure website and product performance`,
      `understand how visitors use our website`,
      `improve product experience`,
      `support marketing and campaign measurement where permitted`,
    ] },
  { type: "h2", text: `2. Types of cookies we use` },
  { type: "h3", text: `Strictly necessary cookies` },
  { type: "p", text: `These are required for the website and app to function. They may support:` },
  { type: "ul", items: [
      `login and authentication`,
      `security`,
      `fraud prevention`,
      `load balancing`,
      `session management`,
      `cookie preference storage`,
    ] },
  { type: "p", text: `You cannot usually disable these through our cookie banner.` },
  { type: "h3", text: `Functional cookies` },
  { type: "p", text: `These help remember choices such as:` },
  { type: "ul", items: [
      `region`,
      `interface preferences`,
      `dismissed banners`,
      `product settings`,
    ] },
  { type: "h3", text: `Analytics cookies` },
  { type: "p", text: `These help us understand usage, performance, and conversion. They may measure:` },
  { type: "ul", items: [
      `pages visited`,
      `buttons clicked`,
      `sign-up flows`,
      `errors`,
      `performance metrics`,
      `product usage trends`,
    ] },
  { type: "p", text: `Where required, we only use analytics cookies with your consent.` },
  { type: "h3", text: `Marketing cookies` },
  { type: "p", text: `These may be used to:` },
  { type: "ul", items: [
      `measure advertising performance`,
      `understand campaign effectiveness`,
      `build audiences`,
      `deliver relevant ads`,
    ] },
  { type: "p", text: `We only use marketing cookies where permitted by law and your choices.` },
  { type: "h2", text: `3. Third-party cookies` },
  { type: "p", text: `Some cookies may be set by third-party providers that help us with analytics, advertising, support, payments, embedded content, or product functionality.` },
  { type: "p", text: `These providers may process data according to their own terms and privacy policies.` },
  { type: "h2", text: `4. Managing cookies` },
  { type: "p", text: `Where required, we ask for consent before placing non-essential cookies.` },
  { type: "p", text: `You can manage your cookie preferences through our cookie banner or preference centre. You can also control cookies through your browser settings.` },
  { type: "p", text: `Blocking all cookies may affect functionality, including login and workspace features.` },
  { type: "h2", text: `5. Changes` },
  { type: "p", text: `We may update this Cookie Policy as our website, app, and providers change.` },
  { type: "h2", text: `6. Contact` },
  { type: "p", text: `Questions about this Cookie Policy can be sent to privacy@[domain].` },
];
