import type { LegalBlock } from "@/lib/legal/types";

export const blocks: LegalBlock[] = [
  { type: "p", text: `Effective date: [INSERT DATE]` },
  { type: "p", text: `AdeHQ is a service operated by NexCache Limited, a company registered in England and Wales under company number [INSERT COMPANY NUMBER] with registered office at [INSERT REGISTERED OFFICE] (“NexCache”, “AdeHQ”, “we”, “us”, or “our”).` },
  { type: "p", text: `This Privacy Policy explains how we collect, use, disclose, store, and protect personal data when you visit our websites, create an account, use AdeHQ, communicate with us, or otherwise interact with our services.` },
  { type: "p", text: `AdeHQ is an AI workforce workspace. Users can create workspaces, invite human teammates, hire AI employees, send messages, upload files, use AI tools, generate artifacts, create tasks, store memory, approve actions, and track work through logs. Because AdeHQ is designed for business collaboration, workspace owners and administrators may have access to certain workspace-level information, settings, usage, members, and content depending on their role.` },
  { type: "p", text: `This Privacy Policy should be read together with our Terms of Service, Cookie Policy, Acceptable Use Policy, AI Terms, and any applicable order form or data processing agreement.` },
  { type: "h2", text: `1. Who we are` },
  { type: "p", text: `For the purposes of UK data protection law, including the UK GDPR and Data Protection Act 2018, NexCache Limited is usually the controller of personal data collected from visitors, account holders, prospects, and customers.` },
  { type: "p", text: `For workspace content submitted by customers and their authorised users, we may act as a processor on behalf of the relevant customer or workspace owner, depending on the context and agreement in place.` },
  { type: "p", text: `Controller contact:
NexCache Limited
[INSERT REGISTERED OFFICE]
Email: privacy@[domain]` },
  { type: "p", text: `If we appoint a Data Protection Officer or EU/UK representative in the future, we will update this policy with their contact details.` },
  { type: "h2", text: `2. Personal data we collect` },
  { type: "p", text: `We may collect the following categories of information.` },
  { type: "h3", text: `Account and profile information` },
  { type: "p", text: `This may include:` },
  { type: "ul", items: [
      `name`,
      `email address`,
      `password authentication data or login method`,
      `profile image or avatar`,
      `company or workspace name`,
      `role, title, or team information`,
      `billing contact information`,
      `account settings and preferences`,
    ] },
  { type: "h3", text: `Workspace and collaboration data` },
  { type: "p", text: `When you use AdeHQ, we may process information created inside your workspace, including:` },
  { type: "ul", items: [
      `workspaces, rooms, topics, and direct messages`,
      `messages sent by human users`,
      `AI employee responses`,
      `tasks, approvals, memories, work logs, artifacts, and reports`,
      `uploaded files and extracted text`,
      `source references and citations`,
      `employee configurations, prompts, role settings, and permissions`,
      `workspace membership, invites, and role assignments`,
      `usage history and activity metadata`,
    ] },
  { type: "h3", text: `AI and tool usage data` },
  { type: "p", text: `We may process information about how AI features are used, including:` },
  { type: "ul", items: [
      `model/provider used`,
      `input and output token counts`,
      `estimated or actual AI cost`,
      `AI Work Hours usage`,
      `AI employee involved`,
      `work type, capability, and runtime metadata`,
      `browser research runs, search queries, source URLs, screenshots, evidence, and reports`,
      `errors, fallback usage, latency, and provider health signals`,
    ] },
  { type: "p", text: `We use this information to operate, secure, debug, improve, and bill for the service. We do not use private workspace content for public marketing without permission.` },
  { type: "h3", text: `Files and integrations` },
  { type: "p", text: `If you upload files or connect integrations, we may process:` },
  { type: "ul", items: [
      `file names, file types, file sizes, and metadata`,
      `file contents where needed to provide search, summarisation, extraction, citation, or AI work features`,
      `integration account identifiers`,
      `access tokens or refresh tokens, where required`,
      `records of actions performed through connected tools`,
    ] },
  { type: "p", text: `For connected tools, we only access the data needed to provide the feature you enable, subject to the permissions you grant.` },
  { type: "h3", text: `Billing and payment information` },
  { type: "p", text: `Where paid services are available, payment processing may be handled by third-party providers such as Revolut Pay. We may collect or receive:` },
  { type: "ul", items: [
      `plan name`,
      `billing email`,
      `payment status`,
      `subscription status`,
      `invoices, receipts, and transaction references`,
      `limited payment metadata`,
    ] },
  { type: "p", text: `We do not store full card numbers unless explicitly handled by a compliant payment provider on our behalf.` },
  { type: "h3", text: `Website and device data` },
  { type: "p", text: `When you visit our website or use AdeHQ, we may automatically collect:` },
  { type: "ul", items: [
      `IP address`,
      `browser type and version`,
      `device type`,
      `operating system`,
      `referring URLs`,
      `pages viewed`,
      `approximate location from IP address`,
      `session and usage events`,
      `cookie identifiers`,
      `error logs and performance data`,
    ] },
  { type: "h3", text: `Communications` },
  { type: "p", text: `If you contact us, request support, join a waitlist, book a demo, answer a survey, or communicate with us, we may collect:` },
  { type: "ul", items: [
      `name`,
      `email address`,
      `company details`,
      `message contents`,
      `support history`,
      `feedback and survey responses`,
    ] },
  { type: "h2", text: `3. Personal data we do not want you to submit` },
  { type: "p", text: `AdeHQ is a business productivity platform. Unless we explicitly support and agree to such processing, you should not submit:` },
  { type: "ul", items: [
      `special category data, such as health, biometric, religious, political, or trade union data`,
      `criminal offence data`,
      `government identity numbers`,
      `payment card numbers in plain text`,
      `passwords, API keys, or secrets in messages or files`,
      `data about children`,
    ] },
  { type: "p", text: `If you use AdeHQ for regulated or sensitive workflows, you are responsible for ensuring you have the required legal basis, permissions, safeguards, and agreements.` },
  { type: "h2", text: `4. How we use personal data` },
  { type: "p", text: `We use personal data to:` },
  { type: "ul", items: [
      `provide, operate, and maintain AdeHQ`,
      `create and manage accounts and workspaces`,
      `authenticate users and prevent unauthorised access`,
      `enable messages, rooms, topics, AI employees, tasks, memory, approvals, files, artifacts, and work logs`,
      `process AI requests and route them through model providers`,
      `provide browser/search/research features`,
      `store workspace context and memory where enabled`,
      `provide customer support`,
      `manage subscriptions, billing, usage, and plan limits`,
      `monitor performance, reliability, abuse, and security`,
      `debug errors and improve the product`,
      `send service, security, billing, and administrative communications`,
      `send marketing communications where permitted`,
      `comply with legal obligations`,
      `enforce our terms and policies`,
      `protect rights, safety, and security`,
    ] },
  { type: "h2", text: `5. Lawful bases for processing` },
  { type: "p", text: `Where UK GDPR applies, we rely on one or more of the following lawful bases:` },
  { type: "h3", text: `Performance of a contract` },
  { type: "p", text: `We process account, workspace, usage, billing, and support data to provide AdeHQ and fulfil our agreement with you or your organisation.` },
  { type: "h3", text: `Legitimate interests` },
  { type: "p", text: `We process certain data for our legitimate interests, including:` },
  { type: "ul", items: [
      `improving and securing the service`,
      `preventing abuse and fraud`,
      `understanding product usage`,
      `debugging errors`,
      `developing new features`,
      `communicating with business users`,
      `protecting our rights and users`,
    ] },
  { type: "p", text: `We only rely on legitimate interests where we consider that those interests are not overridden by your rights and freedoms.` },
  { type: "h3", text: `Consent` },
  { type: "p", text: `We rely on consent where required, such as for certain marketing communications and non-essential cookies.` },
  { type: "h3", text: `Legal obligation` },
  { type: "p", text: `We process data where required to comply with applicable laws, accounting requirements, tax obligations, regulatory requests, or lawful orders.` },
  { type: "h2", text: `6. AI processing and model providers` },
  { type: "p", text: `AdeHQ uses third-party AI model providers and infrastructure providers to deliver AI features. Depending on configuration, these may include providers such as SiliconFlow, Vercel AI Gateway, OpenAI, Anthropic, Google, Perplexity, Tavily, Browserbase, Supabase, Vercel, and other providers.` },
  { type: "p", text: `When an AI feature is used, relevant prompts, messages, files, metadata, or context may be sent to a model provider or tool provider to generate a response, perform search, run browser research, create embeddings, or process a file.` },
  { type: "p", text: `We aim to minimise the information sent to providers and route requests based on the feature being used. We may update providers over time as our runtime, pricing, reliability, and security requirements change.` },
  { type: "p", text: `You should not submit confidential, sensitive, or regulated data to AI features unless your organisation has assessed the risks and has appropriate agreements and settings in place.` },
  { type: "h2", text: `7. Workspace owners and administrators` },
  { type: "p", text: `Workspace owners and administrators may be able to:` },
  { type: "ul", items: [
      `invite and remove members`,
      `assign roles and permissions`,
      `view workspace usage and AI Work Hours`,
      `view workspace members, rooms, topics, tasks, approvals, memory, and work logs`,
      `configure AI employees and tools`,
      `manage billing and plans`,
      `access certain audit and security information`,
    ] },
  { type: "p", text: `If you use AdeHQ through an organisation, your organisation may control your access and may process workspace content in accordance with its own policies.` },
  { type: "h2", text: `8. Sharing personal data` },
  { type: "p", text: `We do not sell personal data.` },
  { type: "p", text: `We may share personal data with:` },
  { type: "ul", items: [
      `hosting and infrastructure providers`,
      `database and authentication providers`,
      `AI model and AI gateway providers`,
      `search and browser automation providers`,
      `analytics and product monitoring providers`,
      `payment and billing providers`,
      `email and communication providers`,
      `customer support and CRM tools`,
      `professional advisers, such as lawyers and accountants`,
      `authorities, regulators, courts, or law enforcement where required`,
      `acquirers or successors in connection with a merger, acquisition, financing, restructuring, or sale of assets`,
    ] },
  { type: "p", text: `We require service providers to process personal data only as needed to provide services to us and subject to appropriate safeguards.` },
  { type: "h2", text: `9. International transfers` },
  { type: "p", text: `Your personal data may be processed in the United Kingdom, the European Economic Area, the United States, and other countries where we or our service providers operate.` },
  { type: "p", text: `Where required, we use appropriate safeguards for international transfers, such as adequacy regulations, standard contractual clauses, the UK International Data Transfer Agreement, or other lawful transfer mechanisms.` },
  { type: "h2", text: `10. Data retention` },
  { type: "p", text: `We retain personal data only for as long as reasonably necessary for the purposes described in this policy.` },
  { type: "p", text: `Typical retention periods may include:` },
  { type: "ul", items: [
      `account data: for the life of the account and a reasonable period after closure`,
      `workspace content: while the workspace exists, unless deleted earlier by authorised users`,
      `billing and transaction records: as required for tax, accounting, and legal purposes`,
      `security logs: for a limited period needed to detect abuse and protect the service`,
      `support communications: for as long as needed to provide support and maintain records`,
      `backups: for a limited backup lifecycle before deletion or overwrite`,
    ] },
  { type: "p", text: `We may retain certain information longer where required by law, to resolve disputes, enforce agreements, prevent abuse, or protect our rights.` },
  { type: "h2", text: `11. Security` },
  { type: "p", text: `We use technical and organisational measures designed to protect personal data, including:` },
  { type: "ul", items: [
      `authentication and access controls`,
      `workspace-level isolation`,
      `server-side authorisation checks`,
      `role-based permissions`,
      `logging and monitoring`,
      `secure handling of environment variables and provider keys`,
      `approval gates for sensitive AI actions`,
      `audit trails and work logs`,
      `encryption in transit`,
      `infrastructure security controls provided by our hosting and database providers`,
    ] },
  { type: "p", text: `No system is completely secure. You are responsible for using strong passwords, protecting account credentials, managing workspace permissions carefully, and avoiding submission of unnecessary sensitive data.` },
  { type: "h2", text: `12. Your rights` },
  { type: "p", text: `Depending on your location and the nature of the processing, you may have rights to:` },
  { type: "ul", items: [
      `access your personal data`,
      `correct inaccurate data`,
      `delete data`,
      `restrict processing`,
      `object to processing`,
      `receive a portable copy of data`,
      `withdraw consent`,
      `complain about our handling of your data`,
    ] },
  { type: "p", text: `To exercise rights, contact privacy@[domain]. We may need to verify your identity and may ask for information to help us process your request.` },
  { type: "p", text: `If your data is controlled by your employer, client, or workspace owner, we may direct your request to that organisation.` },
  { type: "h2", text: `13. Data protection complaints` },
  { type: "p", text: `If you have a concern about how we handle personal data, please contact us first at privacy@[domain] so we can investigate and respond.` },
  { type: "p", text: `You also have the right to complain to the UK Information Commissioner’s Office. The ICO is the UK supervisory authority for data protection. More information is available at ico.org.uk.` },
  { type: "h2", text: `14. Marketing communications` },
  { type: "p", text: `We may send marketing emails to business contacts where permitted by law. You can opt out at any time using the unsubscribe link or by contacting us.` },
  { type: "p", text: `Even if you opt out of marketing, we may still send service, billing, legal, or security communications.` },
  { type: "h2", text: `15. Children` },
  { type: "p", text: `AdeHQ is not intended for children. You must be at least 18 years old, or the age of majority in your jurisdiction, to use AdeHQ unless we have expressly agreed otherwise.` },
  { type: "h2", text: `16. Changes to this policy` },
  { type: "p", text: `We may update this Privacy Policy from time to time. We will post the updated version on this page and update the effective date. If changes are material, we may provide additional notice.` },
  { type: "h2", text: `17. Contact` },
  { type: "p", text: `NexCache Limited
Trading as AdeHQ
[INSERT REGISTERED OFFICE]
Email: privacy@[domain]` },
];
